---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: append host names
      blockinfile:
        dest: /etc/hosts
        content: "{{ lookup('file', '/vagrant/hosts') }}"
    - name: install ceph packages on admin
      yum: name={{item}} state=latest
      with_items:
        - centos-release-ceph-jewel
        - ceph-deploy
    - name: create cephdeploy user and ssh key
      user:
        name: cephdeploy
        comment: "Ceph deploy user"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
